### PR TITLE
KRP-1527 Change account type for the account creation

### PR DESCRIPTION
**Pull request by jablonskipj**
[Addresses](https://kontist.atlassian.net/browse/KRP-1572)
[Parent PR on the BE](https://github.com/kontist/backend/pull/13557)

### CODE REVIEW

**Review by mbayraktr — APPROVED** [review]
🙌

**Comment by mbayraktr** [comment]
you need to patch/upgrade the version either in this pr or different and then update the mock-solaris version on backend.
For patch update:
```
npm version patch
git push --follow-tags
```

**Comment by jablonskipj** [comment]
@mbayraktr could you check if now it is ok?

**Comment by mbayraktr** [comment]
> @mbayraktr could you check if not it is ok?

should be ok 👍

**Pull request merged**
