### PR TITLE
Extend transaction types

### PR DESCRIPTION
**Pull request by lera**

### CODE REVIEW

**Review by Campalo — COMMENTED** [review]
Should `Commision_overdraft` be in CardType ? in the ticket it is written that we have two new TransactionType.

**Comment by lera** [comment]
it's in BookingType if you expand the row 😁

**Comment by Campalo** [comment]
true 😅  

Can you explain why putting it in BookingType and not in TransactionType?

**Comment by lera** [comment]
in TransactionType are subtypes of booking with the booking type 'CARD_TRANSACTION'

**Review by Campalo — APPROVED** [review]

**Pull request merged**
